apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      name: app-deployment
      labels:
        app: app-deployment      # service will connect by this labels
    spec:
      containers:
        - name: app-deployment
          image: berezzin/simple-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secrets
      restartPolicy: Always

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-deployment-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: app-deployment
  minReplicas: 4
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
    env: prod
spec:
  selector:
    app: app-deployment      # Selecting PODs with those Labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 80  # Port on Load Balancer
      targetPort: 8080  # Port on Pod
  type: LoadBalancer